// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jNyBz48ciV5qN-3tmGrCQ4ZXTdyc6w8',
    appId: '1:515027803393:web:e4bef8400140466bbf8f00',
    messagingSenderId: '515027803393',
    projectId: 'green-car-e515a',
    authDomain: 'green-car-e515a.firebaseapp.com',
    databaseURL: 'https://green-car-e515a-default-rtdb.firebaseio.com',
    storageBucket: 'green-car-e515a.firebasestorage.app',
    measurementId: 'G-C6JXZ1RW98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9dzaBITtRqM6BGvEs4_lxC5Acuje1jOY',
    appId: '1:515027803393:android:1f328ba6ade5a82bbf8f00',
    messagingSenderId: '515027803393',
    projectId: 'green-car-e515a',
    databaseURL: 'https://green-car-e515a-default-rtdb.firebaseio.com',
    storageBucket: 'green-car-e515a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlC_JW9UvpKeon1GbrviS3YAAX5mPWbXE',
    appId: '1:515027803393:ios:634f0b6b321f87dabf8f00',
    messagingSenderId: '515027803393',
    projectId: 'green-car-e515a',
    databaseURL: 'https://green-car-e515a-default-rtdb.firebaseio.com',
    storageBucket: 'green-car-e515a.firebasestorage.app',
    iosBundleId: 'com.example.carWashMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlC_JW9UvpKeon1GbrviS3YAAX5mPWbXE',
    appId: '1:515027803393:ios:634f0b6b321f87dabf8f00',
    messagingSenderId: '515027803393',
    projectId: 'green-car-e515a',
    databaseURL: 'https://green-car-e515a-default-rtdb.firebaseio.com',
    storageBucket: 'green-car-e515a.firebasestorage.app',
    iosBundleId: 'com.example.carWashMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jNyBz48ciV5qN-3tmGrCQ4ZXTdyc6w8',
    appId: '1:515027803393:web:80bbfdee760705f9bf8f00',
    messagingSenderId: '515027803393',
    projectId: 'green-car-e515a',
    authDomain: 'green-car-e515a.firebaseapp.com',
    databaseURL: 'https://green-car-e515a-default-rtdb.firebaseio.com',
    storageBucket: 'green-car-e515a.firebasestorage.app',
    measurementId: 'G-0MZBR52RN5',
  );
}